# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NSECt0gtU5MxDLkTtM1TiXxP7nqy4UR
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df=pd.read_csv("/content/Advertising_F.csv")
df.head()

#show administratives
st.title("Advertising Effectiveness Dashboard_EmmyT")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("X-Axis",["TV","radio","newspaper"])
y_var=st.sidebar.selectbox("Y-Axis",["sales"])

#show scatterplot
fig=px.scatter(df,x=x_var,y=y_var,trendline="ols")
st.plotly_chart(fig)

#show the df
st.write("### Data Frame")
st.dataframe(df)

#show a map
st.title("This is the map.")
fig=px.scatter_mapbox(df,lat="latitude",lon="longitude",color="sales",size="TV",hover_name="City")
fig.update_layout(mapbox_style="carto-positron")
st.plotly_chart(fig)